version: '3.8'

services:
  backend:
    build: ./backend/src/TodoApi
    ports:
      - "5090:80"
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
